{% set name = "mofchecker" %}
{% set version = "0.8.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mofchecker-{{ version }}.tar.gz
  sha256: 4b6bccab176b97d30db98520f3da4627310885d5c4763c336f268b4717c8601b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mofchecker = mofchecker.cli:main


requirements:
  host:
    - pip
    - python >=3.6
  run:
    - click ==7.*
    - networkx ==2.*
    - pymatgen >=2021.1,<2022,!=2021.3.4
    - python >=3.6
    - openbabel ==3.*

test:
  imports:
    - mofchecker
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kjappelbaum/mofchecker
  summary: Perform sanity checks on MOF structures
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kjappelbaum
