{% set name = "mofchecker" %}
{% set version = "0.9.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mofchecker-{{ version }}.tar.gz
  sha256: ae370c6454b8f05e7faf305dd4aa32c00e11ed6511181435593c2fe52049751c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mofchecker = mofchecker.cli:main


requirements:
  host:
    - pip
    - python >=3.6
  run:
    - click ==7.*
    - networkx ==2.*
    - pymatgen <2023,>=2022.0.12
    - python >=3.6
    - openbabel ==3.*
    - backports.cached-property ==1.*
    - pyyaml ==5.*
    - ase ==3.*

test:
  imports:
    - mofchecker
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kjappelbaum/mofchecker
  summary: Perform sanity checks on MOF structures
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kjappelbaum
